//
//  DeveloperPreview.swift
//  AirBnbClone
//
//  Created by Avijit bera on 14/03/25.
//

import Foundation

class DeveloperPreview {
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 678,
            latitude: 25.7850,
            longitude: -80.1936,
            address: "123 Main st",
            city: "Miami",
            state: "Florida",
            title: "Miami villa",
            rating: 4.67,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa,
            imageUrls: [ "image-1",
                         "image-2",
                         "image-3",
                         "image-4"]
            
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 678,
            latitude: 25.7850,
            longitude: -80.1936,
            address: "123 Main st",
            city: "Miami",
            state: "Florida",
            title: "Miami villa",
            rating: 4.67,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa,
            imageUrls: [ "image-1",
                         "image-2",
                         "image-3",
                         "image-4"]
            
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 678,
            latitude: 25.7850,
            longitude: -80.1936,
            address: "123 Main st",
            city: "Miami",
            state: "Florida",
            title: "Miami villa",
            rating: 4.67,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa,
            imageUrls: [ "image-1",
                         "image-2",
                         "image-3",
                         "image-4"]
            
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 678,
            latitude: 25.7850,
            longitude: -80.1936,
            address: "123 Main st",
            city: "Miami",
            state: "Florida",
            title: "Miami villa",
            rating: 4.67,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa,
            imageUrls: [ "image-1",
                         "image-2",
                         "image-3",
                         "image-4"]
            
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 678,
            latitude: 25.7850,
            longitude: -80.1936,
            address: "123 Main st",
            city: "Miami",
            state: "Florida",
            title: "Miami villa",
            rating: 4.67,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa,
            imageUrls: [ "image-1",
                         "image-2",
                         "image-3",
                         "image-4"]
            
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 678,
            latitude: 25.7850,
            longitude: -80.1936,
            address: "123 Main st",
            city: "Miami",
            state: "Florida",
            title: "Miami villa",
            rating: 4.67,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .apartment,
            imageUrls: [ "image-1",
                         "image-2",
                         "image-3",
                         "image-4"]
            
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 678,
            latitude: 25.7850,
            longitude: -80.1936,
            address: "123 Main st",
            city: "Miami",
            state: "Florida",
            title: "Miami villa",
            rating: 4.67,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa,
            imageUrls: [ "image-1",
                         "image-2",
                         "image-3",
                         "image-4"]
            
        )
        
    ]
}
